name: render_tests
description: A regression test framework for Dart.
version: 0.1.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/render_tests

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.13.2 <0.14.0'
  glob: '>=1.0.5 <1.1.0'
  path: '>=1.3.9 <1.4.0'
  test: '>=0.12.0 <0.13.0'

dev_dependencies:
  markdown: '>=0.9.0 <0.10.0'
